// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ems/v1/ems.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Name          string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Organizers    []string `protobuf:"bytes,3,rep,name=organizers,proto3" json:"organizers,omitempty"`
	Active        bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	NftPrice      int32    `protobuf:"varint,5,opt,name=nft_price,json=nftPrice,proto3" json:"nft_price,omitempty"`
	TokenPrice    int32    `protobuf:"varint,6,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`
	MaxOrganizers int32    `protobuf:"varint,7,opt,name=max_organizers,json=maxOrganizers,proto3" json:"max_organizers,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab04e176814db968, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetOrganizers() []string {
	if m != nil {
		return m.Organizers
	}
	return nil
}

func (m *Event) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Event) GetNftPrice() int32 {
	if m != nil {
		return m.NftPrice
	}
	return 0
}

func (m *Event) GetTokenPrice() int32 {
	if m != nil {
		return m.TokenPrice
	}
	return 0
}

func (m *Event) GetMaxOrganizers() int32 {
	if m != nil {
		return m.MaxOrganizers
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "ems.v1.Event")
}

func init() { proto.RegisterFile("ems/v1/ems.proto", fileDescriptor_ab04e176814db968) }

var fileDescriptor_ab04e176814db968 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4a, 0xc3, 0x40,
	0x18, 0x85, 0x33, 0xb6, 0x89, 0xcd, 0x88, 0xa2, 0x83, 0x48, 0xa8, 0x30, 0x06, 0x41, 0xc8, 0xaa,
	0x63, 0xf1, 0x06, 0x82, 0x1b, 0x37, 0x4a, 0x96, 0x6e, 0xca, 0x34, 0x4e, 0x93, 0xa1, 0x9d, 0xf9,
	0x43, 0x66, 0x0c, 0xd1, 0x53, 0x78, 0x1c, 0x8f, 0xe0, 0xb2, 0x4b, 0x97, 0x92, 0x5c, 0x44, 0x32,
	0x29, 0xd2, 0xcd, 0xcf, 0x7b, 0xdf, 0x7b, 0xf0, 0xc3, 0xc3, 0xa7, 0x42, 0x19, 0x56, 0xcf, 0x99,
	0x50, 0x66, 0x56, 0x56, 0x60, 0x81, 0x04, 0xbd, 0xac, 0xe7, 0xd3, 0xf3, 0x1c, 0x72, 0x70, 0x88,
	0xf5, 0x6a, 0x48, 0xa7, 0x67, 0x5c, 0x49, 0x0d, 0xcc, 0xdd, 0x01, 0x5d, 0x7f, 0x21, 0xec, 0x3f,
	0xd4, 0x42, 0x5b, 0x42, 0xf0, 0x58, 0x73, 0x25, 0xa2, 0x83, 0x18, 0x25, 0x61, 0xea, 0x34, 0xa1,
	0x18, 0x43, 0x95, 0x73, 0x2d, 0x3f, 0x44, 0x65, 0xa2, 0x51, 0x3c, 0x4a, 0xc2, 0x74, 0x8f, 0x90,
	0x0b, 0x1c, 0xf0, 0xcc, 0xca, 0x5a, 0x44, 0xe3, 0x18, 0x25, 0x93, 0x74, 0xe7, 0xc8, 0x25, 0x0e,
	0xf5, 0xca, 0x2e, 0xca, 0x4a, 0x66, 0x22, 0xf2, 0x63, 0x94, 0xf8, 0xe9, 0x44, 0xaf, 0xec, 0x73,
	0xef, 0xc9, 0x15, 0x3e, 0xb2, 0xb0, 0x16, 0x7a, 0x17, 0x07, 0x2e, 0xc6, 0x0e, 0x0d, 0x85, 0x1b,
	0x7c, 0xa2, 0x78, 0xb3, 0xd8, 0xfb, 0x7c, 0xe8, 0x3a, 0xc7, 0x8a, 0x37, 0x4f, 0xff, 0xf0, 0xfe,
	0xf1, 0xbb, 0xa5, 0x68, 0xdb, 0x52, 0xf4, 0xdb, 0x52, 0xf4, 0xd9, 0x51, 0x6f, 0xdb, 0x51, 0xef,
	0xa7, 0xa3, 0xde, 0xcb, 0x6d, 0x2e, 0x6d, 0xf1, 0xb6, 0x9c, 0x65, 0xa0, 0x58, 0x05, 0x9b, 0x4d,
	0x56, 0x70, 0xa9, 0x0d, 0x7b, 0x55, 0x05, 0xcf, 0xd6, 0x0a, 0x8c, 0xf3, 0xac, 0xe9, 0x77, 0x63,
	0xf6, 0xbd, 0x14, 0x66, 0x19, 0xb8, 0x35, 0xee, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xba, 0x3d,
	0x73, 0xa8, 0x52, 0x01, 0x00, 0x00,
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxOrganizers != 0 {
		i = encodeVarintEms(dAtA, i, uint64(m.MaxOrganizers))
		i--
		dAtA[i] = 0x38
	}
	if m.TokenPrice != 0 {
		i = encodeVarintEms(dAtA, i, uint64(m.TokenPrice))
		i--
		dAtA[i] = 0x30
	}
	if m.NftPrice != 0 {
		i = encodeVarintEms(dAtA, i, uint64(m.NftPrice))
		i--
		dAtA[i] = 0x28
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Organizers) > 0 {
		for iNdEx := len(m.Organizers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Organizers[iNdEx])
			copy(dAtA[i:], m.Organizers[iNdEx])
			i = encodeVarintEms(dAtA, i, uint64(len(m.Organizers[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintEms(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func encodeVarintEms(dAtA []byte, offset int, v uint64) int {
	offset -= sovEms(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovEms(uint64(l))
	}
	if len(m.Organizers) > 0 {
		for _, s := range m.Organizers {
			l = len(s)
			n += 1 + l + sovEms(uint64(l))
		}
	}
	if m.Active {
		n += 2
	}
	if m.NftPrice != 0 {
		n += 1 + sovEms(uint64(m.NftPrice))
	}
	if m.TokenPrice != 0 {
		n += 1 + sovEms(uint64(m.TokenPrice))
	}
	if m.MaxOrganizers != 0 {
		n += 1 + sovEms(uint64(m.MaxOrganizers))
	}
	return n
}

func sovEms(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEms(x uint64) (n int) {
	return sovEms(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEms
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEms
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEms
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Organizers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEms
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEms
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Organizers = append(m.Organizers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftPrice", wireType)
			}
			m.NftPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftPrice |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenPrice", wireType)
			}
			m.TokenPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenPrice |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrganizers", wireType)
			}
			m.MaxOrganizers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOrganizers |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEms(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEms
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEms(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEms
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEms
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEms
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEms
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEms
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEms
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEms        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEms          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEms = fmt.Errorf("proto: unexpected end of group")
)
